// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package lexer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TokenEOF-0]
	_ = x[TokenError-1]
	_ = x[TokenText-2]
	_ = x[TokenNewline-3]
	_ = x[TokenHeader-4]
	_ = x[TokenCodeFence-5]
	_ = x[TokenHorizontalRule-6]
	_ = x[TokenBlockquote-7]
	_ = x[TokenListMarker-8]
	_ = x[TokenBacktick-9]
	_ = x[TokenStar-10]
	_ = x[TokenUnderscore-11]
}

const _TokenType_name = "TokenEOFTokenErrorTokenTextTokenNewlineTokenHeaderTokenCodeFenceTokenHorizontalRuleTokenBlockquoteTokenListMarkerTokenBacktickTokenStarTokenUnderscore"

var _TokenType_index = [...]uint8{0, 8, 18, 27, 39, 50, 64, 83, 98, 113, 126, 135, 150}

func (i TokenType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TokenType_index)-1 {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[idx]:_TokenType_index[idx+1]]
}
