// Code generated by "stringer -type=NodeType"; DO NOT EDIT.

package parser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NodeDocument-0]
	_ = x[NodeParagraph-1]
	_ = x[NodeHeader-2]
	_ = x[NodeBlockquote-3]
	_ = x[NodeCodeBlock-4]
	_ = x[NodeText-5]
	_ = x[NodeEmphasis-6]
	_ = x[NodeStrong-7]
}

const _NodeType_name = "NodeDocumentNodeParagraphNodeHeaderNodeBlockquoteNodeCodeBlockNodeTextNodeEmphasisNodeStrong"

var _NodeType_index = [...]uint8{0, 12, 25, 35, 49, 62, 70, 82, 92}

func (i NodeType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_NodeType_index)-1 {
		return "NodeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NodeType_name[_NodeType_index[idx]:_NodeType_index[idx+1]]
}
